# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.0
language: objective-c
cache: cocoapods
podfile: ExampleRepo/Podfile

env:
global:
- LANG=en_US.UTF-8
- LC_ALL=en_US.UTF-8
- XCODE_WORKSPACE=ExampleRepo/MagiRefresh.xcworkspace
matrix:
- SCHEME="MagiRefresh-Example"


before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod update --project-directory=ExampleRepo
  - pod install --project-directory=ExampleRepo
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=ExampleRepo
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace ExampleRepo/MagiRefresh.xcworkspace -scheme MagiRefresh-Example -sdk iphonesimulator12.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --no-clean
after_success:
  - sleep 3
